### ISSUE TITLE
Wtyczka toya go przestala dzialac

### ISSUE THREAD

**Issue by casper255** [piotrekcrash/kodi#2]
Po prawidlowej instalacji i wpisaniu danych logowania wtyczka toya go laduje przez kilka minut i nie da jej sie uruchomic

**Comment by piotrekcrash** [comment]
Zaraz sprawdzę co jest grane.

**Comment by piotrekcrash** [comment]
> Po prawidlowej instalacji i wpisaniu danych logowania wtyczka toya go laduje przez kilka minut i nie da jej sie uruchomic

Właśnie sprawdziłem i wszystko działa. Podaj jakieś detale:
 - na jakim systemie działa Kodi
 - jaka wersja Kodi

A najlepiej prześlij kodi.log

**Comment by casper255** [comment]
Kodi 18.6 android 9 na mi box s. Za chwile postaram sie wrzucic dziennik bledow

**Comment by casper255** [comment]
![15873095191912440304090958912000](https://user-images.githubusercontent.com/63518124/79691809-dbd79a00-8261-11ea-894b-7391d9d5fc0f.jpg)

**Comment by piotrekcrash** [comment]
@casper255 czy wtyczka ToyaGO kiedykolwiek działała na tym Mi Boxie?

**Comment by casper255** [comment]
Nie. To pierwsza instalacja. Jak w ustawieniach daje odswiez tocwywala

![15873101199475178780578443678138](https://user-images.githubusercontent.com/63518124/79692051-3f15fc00-8263-11ea-9ed8-d7c17349101a.jpg)

**Comment by piotrekcrash** [comment]
@casper255 jutro zerknę na urządzeniu z AndroidTV. Do tej pory osobiście testowałem jedynie na Windows/Linux (CoreELEC)/Linux (Ubuntu)

**Comment by casper255** [comment]
Teraz ruszylo

**Comment by casper255** [comment]
Szkoda ze we wtyczce nie ma pozostalych opcji typu vod

**Comment by piotrekcrash** [comment]
> Szkoda ze we wtyczce nie ma pozostalych opcji typu vod. Przydala by sie pozostala funkcjonalnosc ktora jest w aplikacji

Obecnie nie posiadam konta z aktywnymi usługami jak VOD także nie mam opcji kontynuowania z brakującymi modułami.

**Comment by casper255** [comment]
Gdybym dostarczyl takie konto jest szansa na rozwiniecie wtyczki o pozostaoe funkcjonalnosci?

**Comment by piotrekcrash** [comment]
> Gdybym dostarczyl takie konto jest szansa na rozwiniecie wtyczki o pozostaoe funkcjonalnosci?

Możemy się tak umówić, ale może to trochę potrwać? Jakie moduły przydałyby się najbardziej w kolejności od najważniejszego do najmniej ważnego?

**Comment by casper255** [comment]
Pozostale vod. Nie ma dla mnie znaczenia w jakiej kolejnosci beda dodawane

**Comment by casper255** [comment]
Jak dlugo potrwala by ewentualnie rozbudowa tej wtyczki?

**Comment by piotrekcrash** [comment]
@casper255 pewnie w ciągu kilku dni uporam się z podstawką a później to już tylko dodawanie kolejnych podkategorii VOD

**Comment by casper255** [comment]
Gdzie mam ci przeslac dane do logowania?

**Comment by piotrekcrash** [comment]
@casper255 zmień sobie hasło na jakieś tymczasowe na czas trwania zmian we wtyczce i wyślij na pch@int.pl

**Comment by casper255** [comment]
Wyslane. Czekam na info o kolejnych funkcjonalnosciach. Bede wdzieczny za info na maila

**Comment by motomouse** [comment]
2 dni temu wtyczka przestała działać z IPTV Simple Client. Same streamy we wtyczce Toya GO są dostępne dopiero po wejściu w katalog TV/Dev - te z katalogu głównego nie działają. Kodi 18.6 na Libreelec ( RPi )

**Comment by piotrekcrash** [comment]
@motomouse W repozytorium jest już dostępna wersja beta odświeżonej wtyczki: 2.0.2b
W Ustawieniach jest opcja wygenerowania nowej playlisty do IPTV Simple.
Na dniach powinny pojawić się też kolejne usprawnienia przywracające możliwości starej wersji wtyczki jak automatyczna konfiguracja IPTV Simple czy możliwość wyboru miejsca wyświetlania kanałów w folderze Telewizja lub bezpośrednio po wejściu we wtyczkę z menu dodatki.

**Comment by motomouse** [comment]
@piotrekcrash - w rzeczy samej - nowa playlista jest niejako skrótami do samej wtyczki - brakuje mi zachowania "zwykłej" telewizji. Czekam z niecierpliwością :)

**Comment by piotrekcrash** [comment]
@motomouse nowa playlista też może zostać używa w IPTV Simple, kanały będą widoczne i będą dzialac jako Telewizja.

**Comment by motomouse** [comment]
Da się jej używać w PVR, ale nie działa jak TV. Nie da się "przewijać" kanałów podczas odtwarzania, nie ma EPG podczas odtwarzania, a żeby zmienić kanał trzeba zastopować stream :)

**Comment by piotrekcrash** [comment]
W tym momencie wtyczka jest przepisywana niemal.od zera bo za dużo problematycznych zmian powstało przy migracji do Kodi 18. Możliwe że przywrócę pełna stara funkcjonalność ale to na pewno potrwa. Do tego czasu najlepiej wyłącz automatyczne aktualizacje i zainstaluj wtyczkę w starej wersji:
https://github.com/piotrekcrash/kodi/blob/master/zips/plugin.video.toyago/plugin.video.toyago-1.3.9.zip

**Comment by motomouse** [comment]
@piotrekcrash - na 18.2 działała bez problemu i to w wersji 1.4.3 o ile się nie mylę. W weekend przestała ;-)
Nie zrozum mnie źle - pisząc o działaniu/niedziałaniu nie miałem pretensji, bo doceniam wkład w open-source - chciałem po prostu pomóc. 
Spróbuję podlinkowaną wersję. Dzięki.

**Comment by piotrekcrash** [comment]
@motomouse nie do końca bez problemu serwis w tle dość mocno obciążał działanie Kodi. Śledź zmiany na repozytorium może niedługo pojawi się wersja obsługująca Telewizję w pełni, nie planowałem brać się za to od razu ale skoro jest zainteresowanie to postaram się przywrócić to nieco szybciej.

**Comment by motomouse** [comment]
@piotrekcrash - OK, co do obciążenia nie zauważyłem - na RPi2 B podczas odtwarzania nie zauważyłem obciążenia większego niż 50% ;-)
Ale dzięki - będę obserwował repo.

**Comment by piotrekcrash** [comment]
@motomouse przywróciłem chyba wszystkie możliwości starej wtyczki w nowej wersji 2.3.0
włącznie z Telewizją w pełnym wydaniu. w sekcji PVR jest opcja wygenerowania listy M3U z linka do serwisu w tle i możliwość automatycznego skonfigurowania IPTV Simple.
Można też wyświetlić kanały bezpośrednio w ekranie głównym dodatku - Ustawienia>Telewizja>Kanały w menu początkowym

Jakbyś znalazł jakieś błędy to zgłaszaj postaram się naprawić.
