### ISSUE TITLE
ToyaGo. Możliwość nagrywania programów?

### ISSUE THREAD

**Issue by nalewkababuni** [piotrekcrash/kodi#3]
Czy istnieje możliwość nagrywania programów? Nie widzę tej opcji w menu audycji. Widziałem ją natomiast w Kodi na Windowsie gdy miałem podłączony tuner TV.
Dzięki za wtyczkę. Działa. Miałem tylko problem z rozjechanym EPG, ale wystarczyło przesunąć o 2 godziny w ustawieniach PVR IPTV Simple.

Xiaomi Mi Box, Kodi 18,6.

**Comment by nalewkababuni** [comment]
Okazuje się, że jest coś takiego jak IPTV Recorder, ale nie mogę zmusić go do działania.

**Comment by piotrekcrash** [comment]
@nalewkababuni  IPTV SImple niestety nie ma opcji nagrywania mimo, że jest ona dostępna w API PVR.
Na Windowsie z tunerem TV miałeś pewnie TVheadend i do tego wtyczka PVR tam faktycznie jest nagrywanie i działa bardzo dobrze.

IPTV Recorder - nigdy nie testowałem więc tutaj nie pomogę
