### ISSUE TITLE
ToyaGo. Na wszystkich kanałach jest słaba jakość

### ISSUE THREAD

**Issue by nalewkababuni** [piotrekcrash/kodi#4]
Każdego kanału nie sprawdzałem, ale np. TVP1, TVN24, wszystkie mają 960x544. Da się ustawić lepszą? Bo lepsza jest nadawana.

**Comment by piotrekcrash** [comment]
Lepsza jakość jest dostępna podczas oglądania na go.toya.net.pl ?

**Comment by nalewkababuni** [comment]
Pogrzebałem trochę i okazuje się, że Toya wprowadza w błąd. Jak wchodzi się poprzez stronę, to jest tam ikonka HD. I wychodzi na to, że to ich HD to jest właśnie 960x544. Nadają jeszcze w x368 i x272, tak więc chyba lepiej nie będzie... Sorry, to HD mnie zmyliło. Chyba, że coś źle sprawdzam, to mnie popraw.

**Comment by piotrekcrash** [comment]
Sprawdziłem własnie z ciekawości i wygląda na to, że 960x544 to max. Plik m3u dla TVP1 "HD":

#EXTM3U
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=358529,CODECS="avc1.66.30, mp4a.40.2",RESOLUTION=480x272
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1368008,CODECS="avc1.77.31, mp4a.40.2",RESOLUTION=656x368
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2372173,CODECS="avc1.77.31, mp4a.40.2",RESOLUTION=960x544
