### ISSUE TITLE
Co zrobić, aby program i kanały z Toya pojawiły się w zakładce Telewizja?

### ISSUE THREAD

**Issue by nalewkababuni** [piotrekcrash/kodi#6]
Zainstalowałem wtyczkę ToyaGO i skonfigurowałem. Kliknąłem w ustawieniach "Skonfiguruj IPTV Simple", wszystko przebiegło OK, ale epg i kanałów w zakładce Telewizja nadal nie mam. Co muszę jeszcze zrobić?

**Comment by piotrekcrash** [comment]
@nalewkababuni Po automatycznej konfiguracji powinien wystarczyć restart Kodi.

**Comment by nalewkababuni** [comment]
Ja już sobie poradziłem, ale sam restart nie wystarczał. A konfigurację przeprowadzałem na dwóch różnych urządzeniach (AndroidTV i Windows).

Z tego co pamiętam, to żeby zaczęło działać, musiałem w zakładce "Playlista M3U" samodzielnie wskazać miejsce zapisu pliku. Wcześniej nie można było nawet odczytać ścieżki jaka była tam wskazana (wyglądało to mniej więcej tak: C:\.\.\.\), aby sprawdzić czy plik rzeczywiście się utworzył. Może ścieżka była za długa. Obecnie mam tak:
![2020-06-21_120802](https://user-images.githubusercontent.com/30936261/85221898-e6c0bf00-b3b7-11ea-893d-6a5e66fdc89a.png)

Druga rzecz to jeszcze musiałem ustawić przesunięcie czasowe w EPG na -2 godziny.

Teraz wszystko działa. Jedyny problem jaki mam, jest taki, że np. po powrocie z pracy, chcąc włączyć jakiś program po wejściu w przewodnik, to kanał się nie uruchamia. Wtedy wystarczy wejść we wtyczkę ToyaGo->Telewizja, aby wygenerowały się kanały. Po powrocie do przewodnika już wszystko działa - domyślam się, że po kilku godzinach nieaktywności trzeba utworzyć nowy plik m3u?

**Comment by piotrekcrash** [comment]
@nalewkababuni problem już zgłoszony tutaj:
https://github.com/piotrekcrash/kodi/issues/5
naprawiłem, ale nie dostałem potwierdzenia od zgłaszającego. Spróbuj tą wersję wtyczki:
https://github.com/piotrekcrash/kodi/files/4697170/plugin.video.toyago-2.3.9.zip
i daj znać czy problem nadal się powtarza, jeżeli nie wrzucę tą wersję do repozytorium.

**Comment by nalewkababuni** [comment]
Ok, potestuję i dam znać w tygodniu. Jeszcze jedną rzecz zauważyłem. Brak w EPG programu dla Discovery Channel.

**Comment by nalewkababuni** [comment]
OK, potestowałem trochę i ta wersja działa bez problemów.
