### ISSUE TITLE
hyperion.switch

### ISSUE THREAD

**Issue by notoco** [piotrekcrash/kodi#7]
Hej
Zaczynam zabawę tym skryptem i zastanawiam się na jakiej zasadzie działa tryb cron. Czy on w ogóle działa? Bo w kodzie nic nie widzę. 
I druga rzecz - nie myślałeś o tym:
    os.system("hyperion-remote -D LEDDEVICE")

    os.system("hyperion-remote -E LEDDEVICE")

chociaż wtedy kłócić się może z hyperion.control...

**Comment by piotrekcrash** [comment]
@notoco cron jest wp lanach od dość dawna, niestety nei było czasu. Ale skoro jest zainteresowanie tą fukcją to postaram się na dniach ją dodać.

**Comment by notoco** [comment]
jestem... Sam próbuję, ale za słabo u mnie z pythonem...
Jakby to jeszcze jakoś współpracowało z https://github.com/hyperion-project/hyperion.control a zwłaszcza z wyłączeniem podświetlenia w menu w kodi. Chyba że masz jakiś pomysł jak dodać tę funkcję - czyli wyłączenie podświetlenia w menu kodi - jeno na filmach i tv żeby działało... Byłaby wtedy kompletna wtyczka do obsługi podświetlenia.
Jeśli nie, to metoda z jasnością ledów na 0 jest ok.

**Comment by notoco** [comment]
Zerknij na to, coś takiego sobie spłodziłem... (za dużo zmian żeby tu wrzucać bezpośrednio)
[script.hyperion.switch.zip](https://github.com/piotrekcrash/kodi/files/5585178/script.hyperion.switch.zip)
Dodałem odczyt parametru - on/off/switch
Wywołanie z crontab (coreelec)
```
0 6 * * * kodi-send --action="RunScript(script.hyperion.switch,off)"
0 17 * * * kodi-send --action="RunScript(script.hyperion.switch,on)"
```
Wywołanie z klawiatury:
`<key id="253">RunScript(script.hyperion.switch,switch)</key>
`
nie masz kodu udostępnionego więc nie robię forka ani nic :) na razie na własny użytek

**Comment by notoco** [comment]
I kolejna zmiana - wywalenia hyperion-remote na rzecz połączenia json-rpc - ciut szybciej i mamy o wiele większa kontrolę, możemy sami dopracować co wyłączać a co włączać...
https://github.com/notoco/univPrivate/tree/master/script.hyperion.switch - zerknij 
teraz zacznę męczyć cron

**Comment by piotrekcrash** [comment]
@notoco niestety nie mam już Hyperiona w swoje instalacji więc zmiany i testowanie nie są za bardzo możliwe.
Mogę udostępnić kod źródłowy (chociaż w sumie wszystkie potrzebne pliki są w ostatniej wersji wtyczki) i możesz zrobić własne repozytorium z wprowadzonymi przez siebie zmianami, żeby w ten sposób kontynuować projekt.

**Comment by notoco** [comment]
Ok. Dzięki za info. Ogarnąłem to wszystko, ale podejrzewam że to projekt dla 2-3 osób...
