### ISSUE TITLE
Problem z logowaniem do toya go

### ISSUE THREAD

**Issue by lutek107** [piotrekcrash/kodi#8]
Witam
Zmieniłem login i hasło do telewizji toya go ponieważ od kolegi dostałem wyższy pakiet. Niestety po dokonanej zmianie na liscie dostępnych kanałów nie pojawiają się żadne z wyjątkiem bezpłatnej tv toya. Co może być przyczyną?  Po wpisaniu poprzedniego loginu i hasłą jest ok. Login i hasło do wyższego pakietu jest prawidłowe gdyż korzystam na nim na tablecie.
Z góry dzięki za pomoc.
Pozdrawiam

**Comment by piotrekcrash** [comment]
@lutek107 aktualnie nie posiadam żadnego konta premium na ToyaGo żeby to sprawdzić.
Najlepiej odinstalować wtyczkę z zaznaczeniem opcji o usunięciu wszystkich danych, a następnie zainstalowanie jej ponownie i podanie danych do konta z lepszym pakietem.

**Comment by piotrekcrash** [comment]
Nie widzę żadnej odpowiedzi więc zakładam, że problem został rozwiązany.
